stages:
  scrape:
    cmd: python scripts/scrape.py
    outs:
      - data/raw/problems.json
  download:
    cmd: python scripts/download.py
    deps:
      - data/raw/problems.json
    outs:
      - data/raw/transcripts
  convert:
    cmd: python scripts/convert.py
    deps:
      - data/raw/transcripts
    outs:
      - data/processed/transcripts
